FactoryBot.define do
  factory :api_key do
    association :organization
    sequence(:name) { |n| "API Key #{n}" }
    active { true }

    # Token will be auto-generated by the model callback
  end
end